export const chineseZodiacSigns = [
  {
    name: "Rat",
    years: [1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032],
    element: "Water",
    traits: ["Clever", "Quick-witted", "Resourceful", "Versatile", "Kind"],
    strengths: ["Intelligent", "Adaptable", "Quick-thinking", "Charming"],
    weaknesses: ["Greedy", "Impatient", "Selfish"],
    description: "People born in the Year of the Rat are known for their intelligence and adaptability. They are quick-witted, resourceful, and versatile.",
    compatibility: ["Dragon", "Monkey", "Ox"],
    luckyColors: ["Blue", "Gold", "Green"],
    luckyNumbers: [2, 3, 6],
  },
  {
    name: "Ox",
    years: [1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021, 2033],
    element: "Earth",
    traits: ["Diligent", "Dependable", "Strong", "Determined", "Honest"],
    strengths: ["Reliable", "Patient", "Hardworking", "Determined"],
    weaknesses: ["Stubborn", "Conservative", "Indifferent"],
    description: "People born in the Year of the Ox are known for their diligence and dependability. They are strong, determined, and trustworthy.",
    compatibility: ["Rat", "Snake", "Rooster"],
    luckyColors: ["White", "Yellow", "Green"],
    luckyNumbers: [1, 4, 6],
  },
  {
    name: "Tiger",
    years: [1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034],
    element: "Wood",
    traits: ["Brave", "Competitive", "Confident", "Charismatic", "Impulsive"],
    strengths: ["Courageous", "Energetic", "Confident", "Charismatic"],
    weaknesses: ["Impulsive", "Short-tempered", "Overconfident"],
    description: "People born in the Year of the Tiger are known for their bravery and confidence. They are competitive, charismatic, and natural leaders.",
    compatibility: ["Horse", "Dog", "Pig"],
    luckyColors: ["Blue", "Grey", "Orange", "White"],
    luckyNumbers: [1, 3, 4],
  },
  {
    name: "Rabbit",
    years: [1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035],
    element: "Wood",
    traits: ["Gentle", "Quiet", "Elegant", "Alert", "Quick"],
    strengths: ["Gentle", "Compassionate", "Patient", "Diplomatic"],
    weaknesses: ["Timid", "Conservative", "Self-indulgent"],
    description: "People born in the Year of the Rabbit are known for their gentleness and elegance. They are quiet, alert, and quick-thinking.",
    compatibility: ["Sheep", "Pig", "Dog"],
    luckyColors: ["Red", "Pink", "Purple", "Blue"],
    luckyNumbers: [3, 4, 6],
  },
  {
    name: "Dragon",
    years: [1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024, 2036],
    element: "Earth",
    traits: ["Confident", "Intelligent", "Ambitious", "Perfectionist", "Exuberant"],
    strengths: ["Confident", "Intelligent", "Ambitious", "Charismatic"],
    weaknesses: ["Arrogant", "Impatient", "Stubborn"],
    description: "People born in the Year of the Dragon are known for their confidence and ambition. They are intelligent, perfectionist, and exuberant.",
    compatibility: ["Rat", "Monkey", "Rooster"],
    luckyColors: ["Gold", "Silver", "Greyish White"],
    luckyNumbers: [1, 6, 7],
  },
  {
    name: "Snake",
    years: [1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025, 2037],
    element: "Fire",
    traits: ["Enigmatic", "Intuitive", "Introverted", "Wise", "Charming"],
    strengths: ["Wise", "Intuitive", "Charming", "Determined"],
    weaknesses: ["Jealous", "Suspicious", "Lazy"],
    description: "People born in the Year of the Snake are known for their wisdom and intuition. They are enigmatic, introverted, and charming.",
    compatibility: ["Ox", "Rooster", "Monkey"],
    luckyColors: ["Black", "Red", "Yellow"],
    luckyNumbers: [2, 8, 9],
  },
  {
    name: "Horse",
    years: [1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026, 2038],
    element: "Fire",
    traits: ["Animated", "Active", "Energetic", "Independent", "Free-spirited"],
    strengths: ["Energetic", "Independent", "Intelligent", "Free-spirited"],
    weaknesses: ["Impatient", "Hot-tempered", "Stubborn"],
    description: "People born in the Year of the Horse are known for their energy and independence. They are animated, active, and free-spirited.",
    compatibility: ["Tiger", "Sheep", "Dog"],
    luckyColors: ["Yellow", "Green", "Blue"],
    luckyNumbers: [2, 3, 7],
  },
  {
    name: "Sheep",
    years: [1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027, 2039],
    element: "Earth",
    traits: ["Gentle", "Mild-mannered", "Shy", "Sympathetic", "Creative"],
    strengths: ["Gentle", "Creative", "Sympathetic", "Peaceful"],
    weaknesses: ["Indecisive", "Over-passive", "Pessimistic"],
    description: "People born in the Year of the Sheep are known for their gentleness and creativity. They are mild-mannered, shy, and sympathetic.",
    compatibility: ["Rabbit", "Horse", "Pig"],
    luckyColors: ["Green", "Red", "Purple"],
    luckyNumbers: [2, 7, 8],
  },
  {
    name: "Monkey",
    years: [1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028, 2040],
    element: "Metal",
    traits: ["Sharp", "Smart", "Curious", "Mischievous", "Witty"],
    strengths: ["Intelligent", "Witty", "Curious", "Innovative"],
    weaknesses: ["Arrogant", "Jealous", "Mistrustful"],
    description: "People born in the Year of the Monkey are known for their intelligence and wit. They are sharp, curious, and mischievous.",
    compatibility: ["Rat", "Dragon", "Snake"],
    luckyColors: ["White", "Blue", "Gold"],
    luckyNumbers: [1, 7, 8],
  },
  {
    name: "Rooster",
    years: [1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029, 2041],
    element: "Metal",
    traits: ["Observant", "Hardworking", "Resourceful", "Courageous", "Talented"],
    strengths: ["Hardworking", "Courageous", "Talented", "Confident"],
    weaknesses: ["Selfish", "Arrogant", "Impatient"],
    description: "People born in the Year of the Rooster are known for their hard work and talent. They are observant, resourceful, and courageous.",
    compatibility: ["Ox", "Dragon", "Snake"],
    luckyColors: ["Gold", "Brown", "Yellow"],
    luckyNumbers: [5, 7, 8],
  },
  {
    name: "Dog",
    years: [1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030, 2042],
    element: "Earth",
    traits: ["Loyal", "Honest", "Amicable", "Kind", "Cautious"],
    strengths: ["Loyal", "Honest", "Reliable", "Kind"],
    weaknesses: ["Pessimistic", "Stubborn", "Cynical"],
    description: "People born in the Year of the Dog are known for their loyalty and honesty. They are amicable, kind, and cautious.",
    compatibility: ["Tiger", "Rabbit", "Horse"],
    luckyColors: ["Green", "Red", "Purple"],
    luckyNumbers: [3, 4, 9],
  },
  {
    name: "Pig",
    years: [1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031, 2043],
    element: "Water",
    traits: ["Compassionate", "Generous", "Diligent", "Sociable", "Easy-going"],
    strengths: ["Compassionate", "Generous", "Diligent", "Optimistic"],
    weaknesses: ["Naive", "Over-reliant", "Materialistic"],
    description: "People born in the Year of the Pig are known for their compassion and generosity. They are diligent, sociable, and easy-going.",
    compatibility: ["Rabbit", "Sheep", "Tiger"],
    luckyColors: ["Yellow", "Grey", "Brown", "Gold"],
    luckyNumbers: [2, 5, 8],
  },
];

export const getChineseZodiac = (year) => {
  const index = (year - 4) % 12;
  return chineseZodiacSigns[index];
};

export const getElement = (year) => {
  const elements = ["Wood", "Fire", "Earth", "Metal", "Water"];
  const index = Math.floor((year - 4) % 10 / 2);
  return elements[index];
};

