export const tarotCards = [
  {
    name: "The Fool",
    number: 0,
    arcana: "Major",
    meaning: "New beginnings, innocence, spontaneity, a free spirit",
    reversed: "Recklessness, taken advantage of, inconsideration",
    description: "The Fool represents new beginnings, having faith in the future, being inexperienced, not knowing what to expect, having beginner's luck, improvisation and believing in the universe.",
  },
  {
    name: "The Magician",
    number: 1,
    arcana: "Major",
    meaning: "Manifestation, resourcefulness, power, inspired action",
    reversed: "Manipulation, poor planning, untapped talents",
    description: "The Magician signifies manifestation, resourcefulness, power, and inspired action. You have the tools, resources, and abilities you need to succeed.",
  },
  {
    name: "The High Priestess",
    number: 2,
    arcana: "Major",
    meaning: "Intuition, sacred knowledge, divine feminine, the subconscious mind",
    reversed: "Secrets, disconnected from intuition, withdrawal and silence",
    description: "The High Priestess represents intuition, unconscious knowledge, and inner voice. Trust your instincts and look beyond the obvious.",
  },
  {
    name: "The Empress",
    number: 3,
    arcana: "Major",
    meaning: "Femininity, beauty, nature, nurturing, abundance",
    reversed: "Creative block, dependence on others, emptiness",
    description: "The Empress symbolizes fertility, nurturing, abundance, and the natural world. It represents creativity and the nurturing aspects of life.",
  },
  {
    name: "The Emperor",
    number: 4,
    arcana: "Major",
    meaning: "Authority, establishment, structure, a father figure",
    reversed: "Domination, excessive control, lack of discipline, inflexibility",
    description: "The Emperor represents authority, structure, control, and fatherhood. It signifies stability, power, and protection through organization.",
  },
  {
    name: "The Hierophant",
    number: 5,
    arcana: "Major",
    meaning: "Spiritual wisdom, religious beliefs, conformity, tradition, institutions",
    reversed: "Personal beliefs, freedom, challenging the status quo",
    description: "The Hierophant represents tradition, conformity, morality, and ethics. It suggests following established rules and conventional values.",
  },
  {
    name: "The Lovers",
    number: 6,
    arcana: "Major",
    meaning: "Love, harmony, relationships, values alignment, choices",
    reversed: "Self-love, disharmony, imbalance, misalignment of values",
    description: "The Lovers card represents love, harmony, and relationships. It can also indicate important choices based on your values and beliefs.",
  },
  {
    name: "The Chariot",
    number: 7,
    arcana: "Major",
    meaning: "Control, willpower, success, action, determination",
    reversed: "Lack of control, lack of direction, aggression",
    description: "The Chariot represents determination, willpower, and control. You have the drive and focus to overcome obstacles and achieve your goals.",
  },
  {
    name: "Strength",
    number: 8,
    arcana: "Major",
    meaning: "Strength, courage, persuasion, influence, compassion",
    reversed: "Inner strength, self-doubt, weakness, low energy",
    description: "Strength represents inner strength, courage, patience, and compassion. True power comes from within, not through force.",
  },
  {
    name: "The Hermit",
    number: 9,
    arcana: "Major",
    meaning: "Soul searching, introspection, being alone, inner guidance",
    reversed: "Isolation, withdrawal, rejection, loneliness",
    description: "The Hermit signifies introspection, searching for truth, and inner guidance. Take time for self-reflection and inner wisdom.",
  },
  {
    name: "Wheel of Fortune",
    number: 10,
    arcana: "Major",
    meaning: "Good luck, karma, life cycles, destiny, a turning point",
    reversed: "Bad luck, resistance to change, breaking cycles",
    description: "The Wheel of Fortune represents cycles, fate, and destiny. Life is constantly changing, and what goes around comes around.",
  },
  {
    name: "Justice",
    number: 11,
    arcana: "Major",
    meaning: "Justice, fairness, truth, cause and effect, law",
    reversed: "Unfairness, lack of accountability, dishonesty",
    description: "Justice represents fairness, truth, and cause and effect. Your actions have consequences, and balance will be restored.",
  },
  {
    name: "The Hanged Man",
    number: 12,
    arcana: "Major",
    meaning: "Pause, suspension, letting go, new perspectives",
    reversed: "Delays, resistance, stalling, needing to move on",
    description: "The Hanged Man suggests a need to pause, reflect, and see things from a different perspective. Sometimes letting go leads to enlightenment.",
  },
  {
    name: "Death",
    number: 13,
    arcana: "Major",
    meaning: "Endings, change, transformation, transition",
    reversed: "Resistance to change, unable to move on, fear of transformation",
    description: "Death represents endings, transformation, and new beginnings. It signifies the natural cycle of life and necessary change.",
  },
  {
    name: "Temperance",
    number: 14,
    arcana: "Major",
    meaning: "Balance, moderation, patience, purpose",
    reversed: "Imbalance, excess, lack of long-term vision",
    description: "Temperance represents balance, moderation, and patience. Find the middle ground and blend different aspects of your life harmoniously.",
  },
  {
    name: "The Devil",
    number: 15,
    arcana: "Major",
    meaning: "Shadow self, attachment, addiction, restriction, sexuality",
    reversed: "Releasing limiting beliefs, exploring dark thoughts, detachment",
    description: "The Devil represents bondage, addiction, and being trapped by material desires. It's time to break free from limiting beliefs.",
  },
  {
    name: "The Tower",
    number: 16,
    arcana: "Major",
    meaning: "Sudden change, upheaval, chaos, revelation, awakening",
    reversed: "Fear of change, disaster avoidance, delaying the inevitable",
    description: "The Tower signifies sudden change, revelation, and awakening. Sometimes destruction is necessary for transformation.",
  },
  {
    name: "The Star",
    number: 17,
    arcana: "Major",
    meaning: "Hope, faith, purpose, renewal, spirituality",
    reversed: "Lack of faith, despair, self-trust, disconnection",
    description: "The Star represents hope, faith, and inspiration. After the Tower's destruction comes healing and renewed faith in the future.",
  },
  {
    name: "The Moon",
    number: 18,
    arcana: "Major",
    meaning: "Illusion, fear, anxiety, subconscious, intuition",
    reversed: "Release of fear, repressed emotion, inner confusion",
    description: "The Moon represents illusion, fear, and the subconscious. Things may not be as they seem—trust your intuition.",
  },
  {
    name: "The Sun",
    number: 19,
    arcana: "Major",
    meaning: "Positivity, fun, warmth, success, vitality",
    reversed: "Inner child, feeling down, overly optimistic",
    description: "The Sun represents joy, success, and vitality. It's a time of happiness, celebration, and positive energy.",
  },
  {
    name: "Judgment",
    number: 20,
    arcana: "Major",
    meaning: "Judgment, reflection, evaluation, awakening, absolution",
    reversed: "Lack of self-awareness, doubt, self-loathing",
    description: "Judgment represents reflection, evaluation, and awakening. It's time to review your past and make amends.",
  },
  {
    name: "The World",
    number: 21,
    arcana: "Major",
    meaning: "Completion, accomplishment, fulfillment, sense of belonging",
    reversed: "Seeking personal closure, shortcuts, delays",
    description: "The World represents completion, accomplishment, and fulfillment. You've reached a major milestone and achieved your goals.",
  },
];

export const tarotSpreadTypes = {
  single: {
    name: "Single Card",
    description: "Get guidance for your day with one card",
    cards: 1,
  },
  threeCard: {
    name: "Three Card Spread",
    description: "Past, Present, Future reading",
    cards: 3,
    positions: ["Past", "Present", "Future"],
  },
  celticCross: {
    name: "Celtic Cross",
    description: "Comprehensive 10-card reading",
    cards: 10,
    positions: [
      "Present Situation",
      "Challenge",
      "Distant Past",
      "Recent Past",
      "Possible Future",
      "Near Future",
      "Your Approach",
      "External Influences",
      "Hopes and Fears",
      "Final Outcome",
    ],
  },
};

export const getRandomCards = (count) => {
  const shuffled = [...tarotCards].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count).map((card, index) => ({
    ...card,
    reversed: Math.random() > 0.7, // 30% chance of reversal
    position: index,
  }));
};

