export const zodiacSigns = [
  {
    name: "Aries",
    dates: "March 21 - April 19",
    element: "Fire",
    quality: "Cardinal",
    rulingPlanet: "Mars",
    symbol: "Ram",
    traits: ["Confident", "Courageous", "Enthusiastic", "Impulsive", "Adventurous"],
    strengths: ["Natural leadership", "Optimism", "Initiative"],
    weaknesses: ["Impatience", "Impulsiveness", "Competitiveness"],
    luckyNumbers: [1, 9, 17],
    luckyColors: ["Red", "Orange"],
    compatibleSigns: ["Leo", "Sagittarius", "Gemini", "Aquarius"],
    description: "Aries is a natural born leader, always ready to blaze a trail and take on challenges head-first. They are energetic, passionate, and pioneering individuals who aren't afraid to take risks.",
    loveDescription: "In love, Aries is passionate and direct. They value honesty and excitement in relationships.",
    careerDescription: "Aries excel in leadership roles, entrepreneurship, and competitive fields.",
  },
  {
    name: "Taurus",
    dates: "April 20 - May 20",
    element: "Earth",
    quality: "Fixed",
    rulingPlanet: "Venus",
    symbol: "Bull",
    traits: ["Patient", "Reliable", "Determined", "Practical", "Sensual"],
    strengths: ["Reliability", "Patience", "Persistence"],
    weaknesses: ["Stubbornness", "Possessiveness", "Resistance to change"],
    luckyNumbers: [2, 6, 15, 24],
    luckyColors: ["Green", "Pink", "Earth tones"],
    compatibleSigns: ["Virgo", "Capricorn", "Cancer", "Pisces"],
    description: "Taurus is known for being reliable, practical, and devoted, with a strong appreciation for beauty and comfort. They value stability and security above all.",
    loveDescription: "Taurus is loyal and romantic. They seek long-term commitment and enjoy sensual pleasures.",
    careerDescription: "Taurus thrive in finance, agriculture, art, and any field requiring patience and persistence.",
  },
  {
    name: "Gemini",
    dates: "May 21 - June 20",
    element: "Air",
    quality: "Mutable",
    rulingPlanet: "Mercury",
    symbol: "Twins",
    traits: ["Adaptable", "Outgoing", "Intelligent", "Curious", "Versatile"],
    strengths: ["Communication", "Adaptability", "Intelligence"],
    weaknesses: ["Indecisiveness", "Nervousness", "Inconsistency"],
    luckyNumbers: [3, 12, 21, 30],
    luckyColors: ["Yellow", "Light Blue", "Silver"],
    compatibleSigns: ["Libra", "Aquarius", "Aries", "Leo"],
    description: "Gemini is versatile, expressive, and quick-witted, with a natural curiosity about life and others. They are social butterflies who love to communicate.",
    loveDescription: "Gemini values intellectual connection and freedom in relationships. They need a partner who can keep up with their quick mind.",
    careerDescription: "Gemini excel in communication, media, teaching, writing, and sales.",
  },
  {
    name: "Cancer",
    dates: "June 21 - July 22",
    element: "Water",
    quality: "Cardinal",
    rulingPlanet: "Moon",
    symbol: "Crab",
    traits: ["Intuitive", "Emotional", "Nurturing", "Protective", "Sympathetic"],
    strengths: ["Loyalty", "Emotional intelligence", "Intuition"],
    weaknesses: ["Moodiness", "Over-sensitivity", "Clinginess"],
    luckyNumbers: [2, 7, 16, 23],
    luckyColors: ["White", "Silver", "Pale Blue"],
    compatibleSigns: ["Scorpio", "Pisces", "Taurus", "Virgo"],
    description: "Cancer is highly intuitive and sentimental. They value home, family, and emotional security, and are deeply caring and protective of loved ones.",
    loveDescription: "Cancer is romantic and devoted. They seek emotional security and a deep emotional connection.",
    careerDescription: "Cancer excel in caregiving, hospitality, real estate, and any field requiring empathy.",
  },
  {
    name: "Leo",
    dates: "July 23 - August 22",
    element: "Fire",
    quality: "Fixed",
    rulingPlanet: "Sun",
    symbol: "Lion",
    traits: ["Confident", "Creative", "Generous", "Proud", "Charismatic"],
    strengths: ["Confidence", "Creativity", "Generosity"],
    weaknesses: ["Arrogance", "Stubbornness", "Self-centeredness"],
    luckyNumbers: [1, 5, 19, 23],
    luckyColors: ["Gold", "Orange", "Yellow"],
    compatibleSigns: ["Aries", "Sagittarius", "Gemini", "Libra"],
    description: "Leo is confident, creative, and naturally dramatic. They love being the center of attention and have a generous, warm-hearted nature.",
    loveDescription: "Leo is passionate and loyal in love. They enjoy grand romantic gestures and being adored.",
    careerDescription: "Leo excel in entertainment, leadership, creative arts, and any field where they can shine.",
  },
  {
    name: "Virgo",
    dates: "August 23 - September 22",
    element: "Earth",
    quality: "Mutable",
    rulingPlanet: "Mercury",
    symbol: "Virgin",
    traits: ["Analytical", "Practical", "Detail-oriented", "Modest", "Hardworking"],
    strengths: ["Analytical thinking", "Reliability", "Perfectionism"],
    weaknesses: ["Over-critical", "Worry", "Perfectionism"],
    luckyNumbers: [5, 14, 23, 32],
    luckyColors: ["Navy Blue", "Beige", "Brown"],
    compatibleSigns: ["Taurus", "Capricorn", "Cancer", "Scorpio"],
    description: "Virgo is analytical, practical, and detail-oriented. They have a strong sense of duty and strive for perfection in everything they do.",
    loveDescription: "Virgo is devoted and practical in love. They show love through acts of service and attention to detail.",
    careerDescription: "Virgo excel in healthcare, analysis, research, editing, and any field requiring precision.",
  },
  {
    name: "Libra",
    dates: "September 23 - October 22",
    element: "Air",
    quality: "Cardinal",
    rulingPlanet: "Venus",
    symbol: "Scales",
    traits: ["Diplomatic", "Social", "Fair-minded", "Indecisive", "Peaceful"],
    strengths: ["Diplomacy", "Fairness", "Social skills"],
    weaknesses: ["Indecisiveness", "Avoiding confrontation", "Self-pity"],
    luckyNumbers: [3, 6, 15, 24],
    luckyColors: ["Pink", "Light Blue", "Green"],
    compatibleSigns: ["Gemini", "Aquarius", "Leo", "Sagittarius"],
    description: "Libra values harmony, balance, and justice. They are natural diplomats who seek beauty and peace in all aspects of life.",
    loveDescription: "Libra is romantic and seeks partnership. They value harmony and balance in relationships.",
    careerDescription: "Libra excel in law, diplomacy, design, counseling, and any field requiring balance and fairness.",
  },
  {
    name: "Scorpio",
    dates: "October 23 - November 21",
    element: "Water",
    quality: "Fixed",
    rulingPlanet: "Pluto",
    symbol: "Scorpion",
    traits: ["Intense", "Passionate", "Mysterious", "Determined", "Resourceful"],
    strengths: ["Passion", "Resourcefulness", "Determination"],
    weaknesses: ["Jealousy", "Secretiveness", "Possessiveness"],
    luckyNumbers: [4, 13, 22, 31],
    luckyColors: ["Deep Red", "Black", "Maroon"],
    compatibleSigns: ["Cancer", "Pisces", "Virgo", "Capricorn"],
    description: "Scorpio is intense, passionate, and mysterious. They have deep emotions and are incredibly resourceful and determined.",
    loveDescription: "Scorpio is passionate and loyal in love. They seek deep, transformative connections.",
    careerDescription: "Scorpio excel in research, investigation, psychology, medicine, and fields requiring intensity.",
  },
  {
    name: "Sagittarius",
    dates: "November 22 - December 21",
    element: "Fire",
    quality: "Mutable",
    rulingPlanet: "Jupiter",
    symbol: "Archer",
    traits: ["Adventurous", "Optimistic", "Philosophical", "Honest", "Freedom-loving"],
    strengths: ["Optimism", "Adventure", "Philosophy"],
    weaknesses: ["Impatience", "Tactlessness", "Restlessness"],
    luckyNumbers: [3, 12, 21, 30],
    luckyColors: ["Purple", "Blue", "Red"],
    compatibleSigns: ["Aries", "Leo", "Libra", "Aquarius"],
    description: "Sagittarius is adventurous, optimistic, and philosophical. They love freedom and seek truth and meaning in life.",
    loveDescription: "Sagittarius values freedom and adventure in love. They need a partner who shares their love for exploration.",
    careerDescription: "Sagittarius excel in travel, education, philosophy, publishing, and fields requiring optimism.",
  },
  {
    name: "Capricorn",
    dates: "December 22 - January 19",
    element: "Earth",
    quality: "Cardinal",
    rulingPlanet: "Saturn",
    symbol: "Goat",
    traits: ["Ambitious", "Disciplined", "Practical", "Responsible", "Patient"],
    strengths: ["Ambition", "Discipline", "Responsibility"],
    weaknesses: ["Pessimism", "Rigidity", "Stubbornness"],
    luckyNumbers: [4, 8, 13, 22],
    luckyColors: ["Brown", "Black", "Dark Green"],
    compatibleSigns: ["Taurus", "Virgo", "Scorpio", "Pisces"],
    description: "Capricorn is ambitious, disciplined, and practical. They are natural leaders who work hard to achieve their goals.",
    loveDescription: "Capricorn is serious and committed in love. They seek a partner who shares their values and goals.",
    careerDescription: "Capricorn excel in business, management, finance, and any field requiring discipline and ambition.",
  },
  {
    name: "Aquarius",
    dates: "January 20 - February 18",
    element: "Air",
    quality: "Fixed",
    rulingPlanet: "Uranus",
    symbol: "Water Bearer",
    traits: ["Independent", "Original", "Humanitarian", "Intellectual", "Unconventional"],
    strengths: ["Independence", "Originality", "Humanitarianism"],
    weaknesses: ["Aloofness", "Unpredictability", "Stubbornness"],
    luckyNumbers: [4, 7, 11, 22],
    luckyColors: ["Electric Blue", "Silver", "Aqua"],
    compatibleSigns: ["Gemini", "Libra", "Aries", "Sagittarius"],
    description: "Aquarius is independent, original, and humanitarian. They value freedom and are forward-thinking innovators.",
    loveDescription: "Aquarius values friendship and intellectual connection in love. They need independence and space.",
    careerDescription: "Aquarius excel in technology, science, social work, and innovative fields.",
  },
  {
    name: "Pisces",
    dates: "February 19 - March 20",
    element: "Water",
    quality: "Mutable",
    rulingPlanet: "Neptune",
    symbol: "Fish",
    traits: ["Compassionate", "Intuitive", "Artistic", "Dreamy", "Empathetic"],
    strengths: ["Compassion", "Intuition", "Creativity"],
    weaknesses: ["Over-sensitivity", "Escapism", "Idealistic"],
    luckyNumbers: [3, 7, 12, 16],
    luckyColors: ["Sea Green", "Aquamarine", "Purple"],
    compatibleSigns: ["Cancer", "Scorpio", "Taurus", "Capricorn"],
    description: "Pisces is compassionate, intuitive, and artistic. They are deeply empathetic and have a strong connection to the spiritual realm.",
    loveDescription: "Pisces is romantic and dreamy in love. They seek deep emotional and spiritual connection.",
    careerDescription: "Pisces excel in arts, healing, spirituality, music, and fields requiring creativity and empathy.",
  },
];

export const compatibilityMatrix = {
  Aries: {
    Aries: { score: 75, type: "Great", description: "Dynamic and energetic pair, but may clash due to strong personalities." },
    Taurus: { score: 60, type: "Fair", description: "Different approaches to life, but can learn from each other." },
    Gemini: { score: 85, type: "Excellent", description: "Lively and exciting relationship with great communication." },
    Cancer: { score: 50, type: "Challenging", description: "Different emotional needs may create tension." },
    Leo: { score: 90, type: "Perfect", description: "Passionate and dynamic match with mutual respect." },
    Virgo: { score: 55, type: "Fair", description: "Different priorities, but can balance each other." },
    Libra: { score: 70, type: "Good", description: "Complementary energies with good potential." },
    Scorpio: { score: 65, type: "Good", description: "Intense connection, but may need to manage conflicts." },
    Sagittarius: { score: 88, type: "Excellent", description: "Adventurous and fun-loving partnership." },
    Capricorn: { score: 58, type: "Fair", description: "Different life approaches, requires compromise." },
    Aquarius: { score: 82, type: "Excellent", description: "Independent and exciting relationship." },
    Pisces: { score: 52, type: "Challenging", description: "Very different emotional styles." },
  },
  Taurus: {
    Aries: { score: 60, type: "Fair", description: "Different approaches to life, but can learn from each other." },
    Taurus: { score: 80, type: "Great", description: "Stable and harmonious relationship with shared values." },
    Gemini: { score: 62, type: "Fair", description: "Different communication styles, but can complement." },
    Cancer: { score: 85, type: "Excellent", description: "Emotional and nurturing connection." },
    Leo: { score: 68, type: "Good", description: "Different needs, but can find balance." },
    Virgo: { score: 90, type: "Perfect", description: "Practical and harmonious match." },
    Libra: { score: 75, type: "Great", description: "Shared appreciation for beauty and harmony." },
    Scorpio: { score: 72, type: "Good", description: "Intense and passionate connection." },
    Sagittarius: { score: 58, type: "Fair", description: "Different values and approaches." },
    Capricorn: { score: 88, type: "Excellent", description: "Stable and ambitious partnership." },
    Aquarius: { score: 55, type: "Fair", description: "Very different personalities." },
    Pisces: { score: 80, type: "Great", description: "Sensitive and understanding connection." },
  },
  Gemini: {
    Aries: { score: 85, type: "Excellent", description: "Lively and exciting relationship with great communication." },
    Taurus: { score: 62, type: "Fair", description: "Different communication styles, but can complement." },
    Gemini: { score: 75, type: "Great", description: "Intellectual and communicative match." },
    Cancer: { score: 65, type: "Good", description: "Different emotional needs, but can work." },
    Leo: { score: 82, type: "Excellent", description: "Fun and dynamic partnership." },
    Virgo: { score: 70, type: "Good", description: "Intellectual connection with different approaches." },
    Libra: { score: 90, type: "Perfect", description: "Harmonious and balanced relationship." },
    Scorpio: { score: 58, type: "Fair", description: "Different communication and emotional styles." },
    Sagittarius: { score: 85, type: "Excellent", description: "Adventurous and intellectual match." },
    Capricorn: { score: 60, type: "Fair", description: "Different priorities and values." },
    Aquarius: { score: 92, type: "Perfect", description: "Independent and intellectual partnership." },
    Pisces: { score: 68, type: "Good", description: "Different but complementary energies." },
  },
  Cancer: {
    Aries: { score: 50, type: "Challenging", description: "Different emotional needs may create tension." },
    Taurus: { score: 85, type: "Excellent", description: "Emotional and nurturing connection." },
    Gemini: { score: 65, type: "Good", description: "Different emotional needs, but can work." },
    Cancer: { score: 80, type: "Great", description: "Deep emotional understanding and connection." },
    Leo: { score: 62, type: "Fair", description: "Different emotional expressions." },
    Virgo: { score: 78, type: "Great", description: "Caring and practical partnership." },
    Libra: { score: 70, type: "Good", description: "Harmonious but different emotional styles." },
    Scorpio: { score: 90, type: "Perfect", description: "Intense emotional and spiritual connection." },
    Sagittarius: { score: 55, type: "Fair", description: "Very different emotional needs." },
    Capricorn: { score: 75, type: "Great", description: "Stable and secure relationship." },
    Aquarius: { score: 52, type: "Challenging", description: "Different emotional approaches." },
    Pisces: { score: 88, type: "Excellent", description: "Deep emotional and intuitive connection." },
  },
  Leo: {
    Aries: { score: 90, type: "Perfect", description: "Passionate and dynamic match with mutual respect." },
    Taurus: { score: 68, type: "Good", description: "Different needs, but can find balance." },
    Gemini: { score: 82, type: "Excellent", description: "Fun and dynamic partnership." },
    Cancer: { score: 62, type: "Fair", description: "Different emotional expressions." },
    Leo: { score: 75, type: "Great", description: "Powerful and exciting, but may compete." },
    Virgo: { score: 65, type: "Good", description: "Different approaches, but can complement." },
    Libra: { score: 88, type: "Excellent", description: "Harmonious and romantic partnership." },
    Scorpio: { score: 72, type: "Good", description: "Intense and passionate connection." },
    Sagittarius: { score: 90, type: "Perfect", description: "Adventurous and fun-loving match." },
    Capricorn: { score: 70, type: "Good", description: "Different but complementary goals." },
    Aquarius: { score: 80, type: "Great", description: "Independent and exciting relationship." },
    Pisces: { score: 68, type: "Good", description: "Creative and romantic connection." },
  },
  Virgo: {
    Aries: { score: 55, type: "Fair", description: "Different priorities, but can balance each other." },
    Taurus: { score: 90, type: "Perfect", description: "Practical and harmonious match." },
    Gemini: { score: 70, type: "Good", description: "Intellectual connection with different approaches." },
    Cancer: { score: 78, type: "Great", description: "Caring and practical partnership." },
    Leo: { score: 65, type: "Good", description: "Different approaches, but can complement." },
    Virgo: { score: 80, type: "Great", description: "Practical and organized partnership." },
    Libra: { score: 72, type: "Good", description: "Harmonious but different approaches." },
    Scorpio: { score: 85, type: "Excellent", description: "Intense and analytical connection." },
    Sagittarius: { score: 58, type: "Fair", description: "Very different approaches to life." },
    Capricorn: { score: 88, type: "Excellent", description: "Practical and ambitious partnership." },
    Aquarius: { score: 62, type: "Fair", description: "Different values and priorities." },
    Pisces: { score: 75, type: "Great", description: "Complementary but different styles." },
  },
  Libra: {
    Aries: { score: 70, type: "Good", description: "Complementary energies with good potential." },
    Taurus: { score: 75, type: "Great", description: "Shared appreciation for beauty and harmony." },
    Gemini: { score: 90, type: "Perfect", description: "Harmonious and balanced relationship." },
    Cancer: { score: 70, type: "Good", description: "Harmonious but different emotional styles." },
    Leo: { score: 88, type: "Excellent", description: "Harmonious and romantic partnership." },
    Virgo: { score: 72, type: "Good", description: "Harmonious but different approaches." },
    Libra: { score: 80, type: "Great", description: "Harmonious and balanced partnership." },
    Scorpio: { score: 68, type: "Good", description: "Different but can find balance." },
    Sagittarius: { score: 82, type: "Excellent", description: "Adventurous and balanced match." },
    Capricorn: { score: 75, type: "Great", description: "Stable and harmonious relationship." },
    Aquarius: { score: 85, type: "Excellent", description: "Independent and harmonious partnership." },
    Pisces: { score: 78, type: "Great", description: "Romantic and harmonious connection." },
  },
  Scorpio: {
    Aries: { score: 65, type: "Good", description: "Intense connection, but may need to manage conflicts." },
    Taurus: { score: 72, type: "Good", description: "Intense and passionate connection." },
    Gemini: { score: 58, type: "Fair", description: "Different communication and emotional styles." },
    Cancer: { score: 90, type: "Perfect", description: "Intense emotional and spiritual connection." },
    Leo: { score: 72, type: "Good", description: "Intense and passionate connection." },
    Virgo: { score: 85, type: "Excellent", description: "Intense and analytical connection." },
    Libra: { score: 68, type: "Good", description: "Different but can find balance." },
    Scorpio: { score: 85, type: "Excellent", description: "Intense and transformative partnership." },
    Sagittarius: { score: 60, type: "Fair", description: "Very different approaches to life." },
    Capricorn: { score: 88, type: "Excellent", description: "Intense and ambitious partnership." },
    Aquarius: { score: 55, type: "Fair", description: "Very different personalities." },
    Pisces: { score: 92, type: "Perfect", description: "Deep emotional and spiritual connection." },
  },
  Sagittarius: {
    Aries: { score: 88, type: "Excellent", description: "Adventurous and fun-loving partnership." },
    Taurus: { score: 58, type: "Fair", description: "Different values and approaches." },
    Gemini: { score: 85, type: "Excellent", description: "Adventurous and intellectual match." },
    Cancer: { score: 55, type: "Fair", description: "Very different emotional needs." },
    Leo: { score: 90, type: "Perfect", description: "Adventurous and fun-loving match." },
    Virgo: { score: 58, type: "Fair", description: "Very different approaches to life." },
    Libra: { score: 82, type: "Excellent", description: "Adventurous and balanced match." },
    Scorpio: { score: 60, type: "Fair", description: "Very different approaches to life." },
    Sagittarius: { score: 80, type: "Great", description: "Adventurous and independent partnership." },
    Capricorn: { score: 62, type: "Fair", description: "Different priorities and values." },
    Aquarius: { score: 85, type: "Excellent", description: "Independent and adventurous partnership." },
    Pisces: { score: 68, type: "Good", description: "Different but can inspire each other." },
  },
  Capricorn: {
    Aries: { score: 58, type: "Fair", description: "Different life approaches, requires compromise." },
    Taurus: { score: 88, type: "Excellent", description: "Stable and ambitious partnership." },
    Gemini: { score: 60, type: "Fair", description: "Different priorities and values." },
    Cancer: { score: 75, type: "Great", description: "Stable and secure relationship." },
    Leo: { score: 70, type: "Good", description: "Different but complementary goals." },
    Virgo: { score: 88, type: "Excellent", description: "Practical and ambitious partnership." },
    Libra: { score: 75, type: "Great", description: "Stable and harmonious relationship." },
    Scorpio: { score: 88, type: "Excellent", description: "Intense and ambitious partnership." },
    Sagittarius: { score: 62, type: "Fair", description: "Different priorities and values." },
    Capricorn: { score: 85, type: "Excellent", description: "Ambitious and stable partnership." },
    Aquarius: { score: 68, type: "Good", description: "Different but can complement each other." },
    Pisces: { score: 72, type: "Good", description: "Different but can support each other." },
  },
  Aquarius: {
    Aries: { score: 82, type: "Excellent", description: "Independent and exciting relationship." },
    Taurus: { score: 55, type: "Fair", description: "Very different personalities." },
    Gemini: { score: 92, type: "Perfect", description: "Independent and intellectual partnership." },
    Cancer: { score: 52, type: "Challenging", description: "Different emotional approaches." },
    Leo: { score: 80, type: "Great", description: "Independent and exciting relationship." },
    Virgo: { score: 62, type: "Fair", description: "Different values and priorities." },
    Libra: { score: 85, type: "Excellent", description: "Independent and harmonious partnership." },
    Scorpio: { score: 55, type: "Fair", description: "Very different personalities." },
    Sagittarius: { score: 85, type: "Excellent", description: "Independent and adventurous partnership." },
    Capricorn: { score: 68, type: "Good", description: "Different but can complement each other." },
    Aquarius: { score: 80, type: "Great", description: "Independent and innovative partnership." },
    Pisces: { score: 70, type: "Good", description: "Different but can inspire each other." },
  },
  Pisces: {
    Aries: { score: 52, type: "Challenging", description: "Very different emotional styles." },
    Taurus: { score: 80, type: "Great", description: "Sensitive and understanding connection." },
    Gemini: { score: 68, type: "Good", description: "Different but complementary energies." },
    Cancer: { score: 88, type: "Excellent", description: "Deep emotional and intuitive connection." },
    Leo: { score: 68, type: "Good", description: "Creative and romantic connection." },
    Virgo: { score: 75, type: "Great", description: "Complementary but different styles." },
    Libra: { score: 78, type: "Great", description: "Romantic and harmonious connection." },
    Scorpio: { score: 92, type: "Perfect", description: "Deep emotional and spiritual connection." },
    Sagittarius: { score: 68, type: "Good", description: "Different but can inspire each other." },
    Capricorn: { score: 72, type: "Good", description: "Different but can support each other." },
    Aquarius: { score: 70, type: "Good", description: "Different but can inspire each other." },
    Pisces: { score: 85, type: "Excellent", description: "Deep emotional and spiritual partnership." },
  },
};

export const getCompatibility = (sign1, sign2) => {
  if (!sign1 || !sign2) return null;
  return compatibilityMatrix[sign1]?.[sign2] || null;
};

